stages:
  - tests
  - pages

default:
  image: mambaorg/micromamba
  before_script:
    - micromamba create -y -n simplestac -f environment.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate simplestac
    - micromamba env list

tests:
  stage: tests
  script:
    - pip install -e .
    - pytest -s
  
pages:
  stage: pages
  script:
    - micromamba env update -n simplestac -f environment-doc.yml
    - pip install -e .
    - portray as_html -c pyproject_doc.toml
    - mv site public
  artifacts:
    paths:
      - public
  only:
   - main
   - pages

