stages:
  - pages

pages:
  stage: pages
  image: mambaorg/micromamba
  script:
    - micromamba create -f environment.yml
    - eval "$(micromamba shell hook --shell bash)" 
    - micromamba activate simplestac-doc
    - micromamba env list
    - micromamba install -f environment-docs.yml
    - pip install -e .
    - portray as_html -c pyproject_doc.toml
    - mv site public
  artifacts:
    paths:
      - public
  only:
   - main
   - pages

