stages:
  - tests
  - pages

default:
  image: mambaorg/micromamba

tests:
  stage: tests
  script:
    - micromamba install -c conda-forge -y conda-merge
    - conda-merge environment.yml environment-notebook.yml > /tmp/environment-merge.yml
    - micromamba create -y -n simplestac -f /tmp/environment-merge.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate simplestac
    - micromamba env list
    - pip install -e .
    - pytest -s
  rules:
   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
   - if: $CI_COMMIT_BRANCH =~ /.*/
  
pages:
  stage: pages
  variables:
      GIT_STRATEGY: clone
  script:
    - micromamba install -c conda-forge -y conda-merge
    - conda-merge environment.yml environment-doc.yml > /tmp/environment-merge.yml
    - micromamba create -n simplestac -f /tmp/environment-merge.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate simplestac
    - micromamba env list
    - pip install -e .
    - version=`python -m setuptools_scm --strip-dev`
    - echo $version
    - echo "{\"version\":\"$version\"}" > badges.json
    - cp -r examples docs/
    - jupytext --to markdown docs/examples/*.py
    - portray as_html -c pyproject_doc.toml
    - mv site public
  artifacts:
    paths:
      - public
      - badges.json
  rules:
   - if: $CI_COMMIT_BRANCH == "pages" || $CI_COMMIT_BRANCH == "main"

