stages:
  - tests
  - pages
  - zenodo

default:
  image: mambaorg/micromamba

variables:
  GIT_STRATEGY: clone

tests:
  stage: tests
  script:
    - micromamba install -c conda-forge -y conda-merge
    - conda-merge environment.yml environment-notebook.yml > /tmp/environment-merge.yml
    - micromamba create -y -n simplestac -f /tmp/environment-merge.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate simplestac
    - micromamba env list
    - pip install -e .
    - pytest -s
  rules:
   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #  - if: $CI_COMMIT_BRANCH =~ /.*/
  
pages:
  stage: pages
  variables:
      GIT_STRATEGY: clone
  script:
    - micromamba install -c conda-forge -y conda-merge
    - conda-merge environment.yml environment-doc.yml > /tmp/environment-merge.yml
    - micromamba create -n simplestac -f /tmp/environment-merge.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate simplestac
    - micromamba env list
    - pip install -e .
    - version=`python -m setuptools_scm --strip-dev`
    - echo $version
    - echo "{\"version\":\"$version\"}" > badges.json
    - cp -r examples docs/
    - jupytext --to markdown docs/examples/*.py
    - portray as_html -c pyproject_doc.toml
    - mv site public
  artifacts:
    paths:
      - public
      - badges.json
  rules:
   - if: $CI_COMMIT_BRANCH == "pages" || $CI_COMMIT_BRANCH == "main"

zenodo:
  stage: zenodo
  image: python:3.7
  # rules:
  #  - if: $CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+/
  variables:
    VERSION: v1.1.1 # $CI_COMMIT_TAG   
  script:
    - git fetch --all
    - echo $(git tag)
    - pip install git+https://gitlab.com/sbeniamine/gitlab2zenodo
    - git archive --format zip --worktree-attributes --prefix ${CI_PROJECT_TITLE}-${VERSION}/ --output ${CI_PROJECT_TITLE}-${VERSION}.zip ${VERSION}
    - unzip -l ${CI_PROJECT_TITLE}-${VERSION}.zip
    - g2z-get-meta -i $zenodo_record -o .zenodo.json
    - vdate=$(git log -1 --format=%cd --date=short ${VERSION}) && echo "${vdate}" && sed -i "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/${vdate}/g" .zenodo.json
    - cat .zenodo.json
    - g2z-send -t $zenodo_token -m .zenodo.json -v ${VERSION} ${CI_PROJECT_TITLE}-${VERSION}.zip
