name: simplestac
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required
  - ipykernel
  - jsonschema
  - path
  - python
  - rioxarray
  - rio-cogeo
  - stackstac
  - tqdm
  # issue with numpy >= 2.0
  - numpy<2.0

  # dependencies of stac-static and stac-geoparquet
  # otherwise installed pip packages link to wrong stdc++ lib...
  - git
  - geopandas
  - pygeofilter
  - pystac
  - pyarrow
  - pip
  - pip:
    # - stac_geoparquet
    # - git+https://github.com/jsignell/stac-static
    - git+https://forgemia.inra.fr/umr-tetis/stac/simplestac

  # testing
  - pytest
  - pytest-cov