name: simplestac
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  # required
  - tqdm
  - ipykernel
  - path
  - rioxarray
  - stackstac

  # dependencies of stac-static and stac-geoparquet
  # otherwise installed pip packages link to wrong stdc++ lib...
  - geopandas
  - pygeofilter
  - pystac
  - pyarrow
  - pip
  - pip:
    # - stac_geoparquet
    # - git+https://github.com/jsignell/stac-static
    - git+https://gitlab.irstea.fr/umr-tetis/stac/simplestac

  # testing
  - pytest
  - pytest-cov